# Generated by Django 4.2 on 2025-02-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('token', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'otp_email',
                'verbose_name_plural': 'otp_email',
            },
        ),
        migrations.CreateModel(
            name='OtpPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.SmallIntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'otp_phone_number',
                'verbose_name_plural': 'otp_phone_numbers',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='token',
        ),
    ]
