# Generated by Django 4.2 on 2025-04-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpemail',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='otpphonenumber',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
